# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('profile_img', models.CharField(max_length=50)),
                ('weight', models.FloatField(default=70.0)),
                ('stats', models.CharField(max_length=200)),
            ],
        ),
    ]
